import streamlit as st
import pandas as pd
import requests
import json
import google.generativeai as genai
import time
from urllib.parse import quote

# Page Config
st.set_page_config(page_title="Retention Radar", page_icon="📡", layout="wide")

# Title and Sidebar
st.title("📡 Retention Radar")
st.sidebar.header("Configuration")

# Credentials Inputs
SPUR_API_KEY = st.sidebar.text_input("Spur API Bearer Token", type="password", help="Found in Spur Settings > API")
GEMINI_API_KEY = st.sidebar.text_input("Gemini API Key", type="password", help="Get it from aistudio.google.com")

WHATSAPP_NUMBER_SOURCE = "whatsapp" # Default channel

# 1. File Uploader
uploaded_file = st.file_uploader("Upload Metabase/Posthog CSV", type=["csv"])

if uploaded_file:
    # Load Data
    df = pd.read_csv(uploaded_file)
    
    # 2. Pre-process Data
    if 'Last_Login_Days' in df.columns:
        # Filter for At Risk Users (> 7 days inactive)
        risk_df = df[df['Last_Login_Days'] > 7].copy()
        
        # 3. The AI Drafter
        st.write("---")
        st.subheader(f"🚨 At Risk Users ({len(risk_df)})")
        
        if st.checkbox("Generate AI Drafts", value=False, help="Check this to use Gemini to write messages. Uncheck to use a simple template."):
             if not GEMINI_API_KEY:
                 st.warning("⚠️ Please enter your Gemini API Key in the sidebar to generate AI drafts.")
                 # Fallback function
                 def draft_fallback(row):
                    days = int(row['Last_Login_Days']) if pd.notnull(row['Last_Login_Days']) else 0
                    name = row.get('Name', 'there')
                    if pd.isna(name): name = 'there'
                    return f"Hey {name}, it's been {days} days. We miss you!"
                 risk_df['Draft_Message'] = risk_df.apply(draft_fallback, axis=1)
             else:
                 # Configure Gemini
                 genai.configure(api_key=GEMINI_API_KEY)
                 model = genai.GenerativeModel('gemini-1.5-flash')
                 
                 with st.spinner("Gemini is drafting messages..."):
                     def draft_with_ai(row):
                         days = int(row['Last_Login_Days']) if pd.notnull(row['Last_Login_Days']) else 0
                         name = row.get('Name', 'there')
                         if pd.isna(name): name = 'there'
                         
                         prompt = f"""
                         Write a short, friendly, and persuasive WhatsApp recovery message (maximum 20 words) for a customer named '{name}' who hasn't logged into our app for {days} days.
                         Do not include hashtags. Do not include 'Subject:'. Just the message body.
                         """
                         try:
                             response = model.generate_content(prompt)
                             return response.text.strip()
                         except Exception as e:
                             return f"Error: {str(e)}"
                             
                     # Apply AI to dataframe (might be slow for large lists, okay for demo)
                     risk_df['Draft_Message'] = risk_df.apply(draft_with_ai, axis=1)
                     st.success("Drafts generated by Gemini 1.5 Flash!")
        else:
             # Standard Rule-Based Fallback
             def draft_standard(row):
                days = int(row['Last_Login_Days']) if pd.notnull(row['Last_Login_Days']) else 0
                name = row.get('Name', 'there')
                if pd.isna(name): name = 'there'
                return f"Hey {name}, noticed it's been {days} days since your last login. We miss you! Need any help getting back on track?"

             risk_df['Draft_Message'] = risk_df.apply(draft_standard, axis=1)

        # Show interactive table
        edited_df = st.data_editor(
            risk_df[['Name', 'Phone', 'Last_Login_Days', 'Draft_Message']],
            num_rows="dynamic",
            key="editor"
        )

        # 4. The Sending Logic
        if st.button("Send Recovery Messages to All"):
            if not SPUR_API_KEY:
                st.error("Please enter your Spur API Key in the sidebar first!")
            else:
                progress_bar = st.progress(0)
                success_count = 0
                
                for index, row in edited_df.iterrows():
                    phone = str(row['Phone']).replace("+", "").strip() 
                    if phone.endswith('.0'): phone = phone[:-2]
                        
                    message_text = row['Draft_Message']
                    
                    # 1. Encode message for Image URL
                    encoded_text = quote(message_text)
                    image_url = f"https://api.spurnow.com/screenshot/text-message?text={encoded_text}"
                    
                    # 2. Construct Payload
                    payload = {
                        "channel": "whatsapp",
                        "to": phone,
                        "content": {
                            "type": "template",
                            "template": {
                                "name": "support_ticket_update_spur",
                                "language": {"code": "en"},
                                "components": [
                                    {
                                        "type": "header",
                                        "parameters": [
                                            {
                                                "type": "IMAGE",
                                                "image": {"link": image_url}
                                            }
                                        ]
                                    },
                                    {
                                        "type": "body",
                                        "parameters": [
                                            {"text": "", "type": "text"}
                                        ]
                                    },
                                    {
                                        "type": "button",
                                        "index": 0,
                                        "sub_type": "QUICK_REPLY",
                                        "parameters": [
                                            {"type": "payload", "payload": "recovery_flow"}
                                        ]
                                    }
                                ]
                            }
                        }
                    }

                    # 3. Send Request
                    headers = {
                        'Authorization': f'Bearer {SPUR_API_KEY}',
                        'Content-Type': 'application/json'
                    }
                    
                    try:
                        response = requests.post(
                            'https://api.spurnow.com/send-message', 
                            headers=headers, 
                            data=json.dumps(payload)
                        )
                        
                        if response.status_code == 200:
                            success_count += 1
                        else:
                            st.error(f"Failed for {phone}: {response.text}")
                            
                    except Exception as e:
                        st.error(f"Error sending to {phone}: {str(e)}")
                    
                    progress_bar.progress((index + 1) / len(edited_df))

                st.success(f"Done! Sent {success_count} messages.")

    else:
        st.warning("CSV must contain 'Last_Login_Days' column to detect churn.")
